version: "3.8"
services:
  backend:
    image: edenlee6473/aiagent-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    shm_size: "1g"
    environment:
      - HEADLESS=1
    volumes:
      - ./screenshots:/app/screenshots   # <--- shared volume

  frontend:
    image: edenlee6473/aiagent-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./screenshots:/app/screenshots   # <--- shared volume
